### ISSUE TITLE
Robot battery power dies quickly

### ISSUE THREAD

**Issue by Kukanani** [si-machines/poli2#27]
We ran the arm for about 15 minutes, then attempted to raise the pillar. The battery died before the pillar reached full height, rendering the pillar and onboard computers inoperable

**Comment by Kukanani** [comment]
I would like to add a `hardware` label, but don't seem to have that privilege.

**Comment by prashantrao** [comment]
The power cable running through the pillar got caught on the top plate and snapped internally. The battery is normal. I have temporarily fixed the issue and will finalize a formal fix tomorrow.

**Comment by maxsvetlik** [comment]
The cable has been fixed and the aux battery is in place. Closing this for now.
