### ISSUE TITLE
Serial-USB connector physical interference

### ISSUE THREAD

**Issue by Kukanani** [si-machines/poli2#28]
`hardware`
The USB-to-serial interface used to drive the camera pan tilt unit is attached directly to the Skull Canyon NUC. The positioning is such that the connector is forced into an awkward angle, which could cause damage over time.

**Comment by prashantrao** [comment]
Point noted, I will prepare a better connector. Thanks for bringing this up!

**Comment by Kukanani** [comment]
Fixed for quite some time now.
