### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by maxsvetlik** [si-machines/poli2#33]
This can be open issue that people can voice areas that they feel documentation is lacking and/or incorrect.

Ideally once someone is aware that something is incorrect, they can fix it by making changes and committing to the `documentation` branch.

For things that will change frequently (like How-Tos for software) we use the [github wiki](https://github.com/si-machines/poli2/wiki/).

**Comment by maxsvetlik** [comment]
- [ ] Remove details about old gripper
- [ ] Add details about new gripper

**Comment by maxsvetlik** [comment]
- [ ] Arduino development / how to flash new code to arduinos / dependent libraries

**Comment by maxsvetlik** [comment]
- [ ] Tilt motor launching script
- [ ] Wiring diagrams for each microcontroller
- [ ] Power block diagram
- [ ] Port names for each microcontroller

**Comment by maxsvetlik** [comment]
[ ] - new charging scheme (removing two plugs from charging block, rather than removing serial charger from base)
[ ] - charging the aux battery
[ ] - plugging / unplugging / turning on aux battery

**Comment by Kukanani** [comment]
The LaTeX documentation has been superseded and the issues listed are either fixed or no longer relevant.
