### ISSUE TITLE
URDF does not reflect robot's gripper

### ISSUE THREAD

**Issue by maxsvetlik** [si-machines/poli2#34]
The URDF has the Weiss gripper as attached to the arm. This no longer reflects the actual robot state and should be changed to use the new gripper.

Additionally, the defacto gripper driver will no longer work as it is Weiss exclusive. A new driver will need to be found, added and integrated.

**Comment by maxsvetlik** [comment]
MoveIt's SRDF will also need to be generated from the URDF. More specifically, convert from Xacro -> URDF and rerun setup_assistant

**Comment by maxsvetlik** [comment]
The lack of a working driver causes issues for the TF tree. As a consequence, I've removed the arm from the URDF (commented out) and the `poli2_upstart` launch files. 

These should be added back and re-integrated once the gripper is added to the arm and the gripper driver is working.

**Comment by Kukanani** [comment]
All issues here have been fixed except for one: the Robotiq does not update its state in RViz/MoveIt to reflect the actual gripper state.

**Comment by Kukanani** [comment]
Fixed by e910221
