### ISSUE TITLE
Pan controller driver dies

### ISSUE THREAD

**Issue by maxsvetlik** [si-machines/poli2#40]
Roughly 50% of the time, launching the pan driver results in the node dying immediately after initializing the dynamixel. 

    [ERROR] [1518804225.428219224]: Cant' Load Dynamixel, Please check Parameter [poli_pan_position_control-1] process has died

This happens launching the pan_controller standalone or in a group, so it does not seem to be in conflict with other devices or some sort of race.

**Comment by Kukanani** [comment]
Fixed with current baud rate and connection setup.
